#!/usr/bin/env python3

import os
import os.path
import argparse
from hashlib import md5


parser = argparse.ArgumentParser(description="Rename photos cryptographically to give them more generic and unified names")
parser.add_argument("-v", "--verbose", help="increase output verbosity", action="store_true")
parser.add_argument("-a", "--all", help="rename all files in the current directory", action="store_true")
parser.add_argument("-i", "--input_file", help="set the input file to be renamed", type=str)
parser.add_argument("-o", "--output_path", help="set the output files location", type=str)
parser.add_argument("--md5", help="use md5 to rename output file", action="store_true")
args = parser.parse_args()

if args.md5:
	if args.verbose:
		print("Input File: " + os.path.realpath(args.input_file))
	input_photo = os.path.realpath(args.input_file)
	file_name, file_extention = os.path.splitext(input_photo)
	if args.output_path:
		output_path = os.path.realpath(args.output_path) + '/'
	else:
		output_path = os.getcwd() + '/'
	m = md5()
	m.update(args.input_file.encode('utf-8'))
	md5string = str(m.hexdigest())
	output_photo = (output_path+md5string+file_extention)
	print("Output File: " + output_photo)
	os.rename(input_photo, output_photo)

